const fs = require('fs')


function toUpperCaseCharacter(int) {
    return String.fromCharCode(96 + int - 32)
}


function declarationStatement(int) {
    const lines = ['export declare function pipe<']
    for (let i = 0; i < int + 1; i++) {
        const character = toUpperCaseCharacter(i + 1)
        lines.push(`\t${character},`)
    }
    lines.push('>(')
    lines.push('\tvalue: A,')
    let next
    for (let i = 0; i < int; i++) {
        const character = toUpperCaseCharacter(i + 1)
        next = toUpperCaseCharacter(i + 2)
        lines.push(`\tfunc${character}: (value: ${character}) => ${next},`)
    }
    lines.push(`): ${next}`)
    return lines.join('\n')
}


function main() {
    const lines = [
        '// Note: these typings are generated by a script',
        '// See generateTypings.js'
    ]
    for (let i = 2; i < 26; i++) {
        const statement = declarationStatement(i)
        lines.push(statement)
    }
    const joined = lines.join('\n')
    fs.writeFileSync('./dist/index.d.ts', joined)
}


if (require.main === module) {
    main()
}
